---
- name: Create VM HDDs
  local_action: 
    module: gce_pd 
    name: "{{item.key}}-hdd" 
    size_gb: "{{ item.value.hdd }}"
    zone: "{{ gce_zone }} "
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}" 
    image: "{{item.value.image}}"
    state: "active"
  with_dict: "{{ gce_vm_list }}"
  tags: vm,hdd

- name: Launch instances
  local_action: 
    module: gce 
    instance_names: "{{item.key}}"
    machine_type: "{{item.value.type}}" 
    disks: "{{ item.key }}-hdd" 
    zone: "{{gce_zone}}" 
    service_account_email: "{{ gce_service_account_email }}" 
    pem_file: "{{ gce_pem_file }}" 
    project_id: "{{ gce_project_id }}" 
    tags: "{{ item.value.inventorygroup }}"
    state: "active"
  register: gceinventory
  with_dict: "{{ gce_vm_list }}"
  tags: vm,launch

- name: add tags to instances
  local_action: 
    module: gce_tag 
    instance_name: "{{ item.key }}" 
    tags: "{{item.value.tags}}"
    zone: "{{gce_zone}}" 
    state: present 
    service_account_email: "{{ gce_service_account_email }}" 
    pem_file: "{{ gce_pem_file }}" 
    project_id: "{{ gce_project_id }}"
  with_dict: "{{ gce_vm_list }}"
  tags: vm,tag


- name: Wait for SSH to come up
  wait_for: host={{ item.1.public_ip }} port=22 timeout=120
  with_subelements: 
    - '{{gceinventory.results}}'
    - instance_data


- name: Add VM to group
  add_host: name="{{ item.0.instance_names.0 }}" ansible_ssh_host="{{item.1.public_ip}}" groupname="{{item.0.invocation.module_args.tags.0}}"
  with_subelements: 
    - '{{gceinventory.results}}'
    - instance_data
  changed_when: "1 == 0"   
